DjangoLevelFour/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views



app_name = 'basic_app'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('other/', views.other, name = 'other'),
    path('relative/', views.relative, name = 'relative'),
]

DjangoLevelFour/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

DjangoLevelFour/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

DjangoLevelFour/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "basic_app/index.html")


def other(request):
    return render(request, "basic_app/other.html")


def relative(request):
    return render(request, "basic_app/relative_url_template.html")

DjangoLevelFour/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Base Template</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'basic_app:index' %}">BRAND</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            <!-- Anything outside of this will be inherited if you extend -->
            {% endblock %}
        </div>
    </body>
</html>

DjangoLevelFour/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>WELCOME TO INDEX</h1>
        <h2>This is index.html showing</h2>
    {% endblock %}

DjangoLevelFour/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>WELCOME TO THE OTHER PAGE</h1>
        <h2>This is an example of template inheritance</h2>
    {% endblock %}

DjangoLevelFour/learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Relative Url page</title>
</head>
<body>
    <div>
        <h1>Welcome to the relative url page</h1>
        <a href="{% url 'basic_app:other' %}">RELATIVE PAGE</a>
        <a href="{% url 'admin:index'  %}">ADMIN PAGE</a>
    </div>
</body>
</html>